---
- hosts: localhost
  vars:
    http_port: 80
    max_clients: 200
  remote_user: root
  tasks:
# =========================================
# Adicionando Repositorios
# =========================================
  - name: Instalando Repositorio Mysql
    yum:
     name: http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm
     state: latest

  - name: Instalando IUS Community Repo
    yum:
     name: https://dl.iuscommunity.org/pub/ius/stable/CentOS/7/x86_64/ius-release-1.0-15.ius.centos7.noarch.rpm
     state: latest

  - name: Yum update...
    yum:
     name: "*"
     state: latest

# =========================================
# Adicionando Pacotes Basicos
# =========================================

  - name: Instalando Mysql
    yum:
     name: mysql-server
     state: latest
     update_cache: yes

# =========================================
# Configurando arquivos e permissoes
# =========================================

  - name: Copia my.cnf /etc
    copy: 
     src: /tmp/my.cnf
     dest: /etc/my.cnf
     backup: yes

  - name: Corrige permissoes /var/lib/mysql
    file:
     path: /var/lib/mysql
     state: directory
     owner: mysql
     group: mysql
    
  - name: Cria dbs Padrao Mysql
    command: mysql_install_db --user=mysql --datadir="/var/lib/mysql" --rpm --keep-my-cnf

  - name: Inicia Banco
    command: "/usr/bin/mysqld_safe --bind-address=0.0.0.0"

#  - name: Cria db SIP
#    command: "mysqladmin create sip"

#  - name: Cria db SEI
#    command: "mysqladmin create sei"

#  - name: Importa Esquema SEI
#    command: "mysql sei < /tmp/sei_mysql.sql"

#  - name: Importa Esquema SIP
#    command: "mysql sip < /tmp/sip_mysql.sql"
